import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Snow from './component/Snow';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section id="snow-section" class="snow-section relative">
      <div class="container mx-auto">
          <div class="grid grid-cols-1 md:grid-cols-3 gap-5 md:gap-10 items-center">
              <div class="message-box text-center">
                  <h3 class="text-white text-2xl">snow one</h3>
              </div>
              <div class="message-box text-center">
                  <h3 class="text-white text-2xl">snow two</h3>
              </div>
              <div class="message-box text-center">
                  <h3 class="text-white text-2xl">snow three</h3>
              </div>
          </div>
      </div>
      <Snow />
    </section>
    </>
  )
}
